<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What problem are you having with your_1922ff</name>
   <tag></tag>
   <elementGuidId>846ceb94-5be5-4018-b5eb-2f1608189b20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formProblem_continueButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formProblem_continueButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8be11b5-d436-4535-ac96-e1635bd839ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>252983d6-bec6-4dde-a040-ff2a58d90428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continueButton</value>
      <webElementGuid>7fef03fd-3500-4f5d-8c94-2ebb695ccc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formProblem_continueButton</value>
      <webElementGuid>12b271ca-2a4f-4b87-8207-e865ac7a4a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>e54326cd-17a1-43b0-9119-ba46593cd0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>verifyProblem()</value>
      <webElementGuid>2a90fca0-6c35-47bf-9f69-1b15f0f7ffc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-button btn btn-primary regButton</value>
      <webElementGuid>6f8e9b59-8e14-4c12-b618-dcb2ac0fcc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formProblem_continueButton&quot;)</value>
      <webElementGuid>8cea2ecb-f309-4c71-b37c-528b52f607a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formProblem_continueButton']</value>
      <webElementGuid>2dd728f0-f823-46c6-8493-c76fcb4afb1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1info']/div/div/input</value>
      <webElementGuid>689a3d9c-eb22-49f4-8795-1c8ee8462a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>19d111d2-4eb6-4ed5-a1d9-dbe3b22105c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'continueButton' and @id = 'formProblem_continueButton']</value>
      <webElementGuid>6884a00c-31d9-42bc-831f-d6ba9b2d5381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
