<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your username_back</name>
   <tag></tag>
   <elementGuidId>5a3b67b4-7735-44ee-9d8f-b01a50626818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_back</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_back']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Back&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b89e0cfa-7c1a-42e9-a045-a0d6dcf3923b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a386896f-d6ae-4794-abd7-120a09903187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>back</value>
      <webElementGuid>57558386-ba9e-490d-9e7b-6a8c4c0715df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_back</value>
      <webElementGuid>aad8ee20-d928-4ee4-abc1-cde7048e5eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>7a9ba0b6-2488-44c1-bdac-33e3096f757a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>backtoProblem()</value>
      <webElementGuid>8af208b1-7c12-4a5e-8b44-405c2040af02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-button btn btn-primary signupbackButton</value>
      <webElementGuid>7fcfd0f9-e8a1-490a-9b0c-67d4821fb9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_back&quot;)</value>
      <webElementGuid>1fdb040d-e280-46ff-bfcf-f963dd9e6021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_back']</value>
      <webElementGuid>796b3ca2-3b05-4df6-b7b2-d62f5397f851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='activationEmail']/div[4]/input</value>
      <webElementGuid>34a9919e-7faa-44a5-bd57-73cfdc33c763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>acf993c2-a2b5-430c-ab4e-75ba5c4ea0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'back' and @id = 'form_back']</value>
      <webElementGuid>ea3e3940-697f-40fe-b19e-573964d14d1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
