<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select reset method--Send reset me_765839</name>
   <tag></tag>
   <elementGuidId>c707121f-ac55-4842-977f-091635d445f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_resetMethod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='form_resetMethod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#form_resetMethod</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0d301551-2e5a-4816-8259-92dcfa0a1040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>resetMethod</value>
      <webElementGuid>a424b0b4-3d76-44f6-a613-4820da1a0241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_resetMethod</value>
      <webElementGuid>a07e997c-34ae-4cd0-9c88-ffb2e158ddb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a6a96f46-07f7-4692-aa3a-d80a8704374a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield w100 form-control m-b</value>
      <webElementGuid>b4cc6763-0e71-4605-ae6f-6037d6d95aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select reset method--Send reset message to mobile</value>
      <webElementGuid>9f76bb3b-76c3-4d4d-9370-dea2c0550aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_resetMethod&quot;)</value>
      <webElementGuid>69abfd20-e2e8-47d0-b95c-37015e0935e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='form_resetMethod']</value>
      <webElementGuid>f73d14b4-1378-4e30-8454-f4d9f3aa52b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resetMethodDiv']/select</value>
      <webElementGuid>e6b8baeb-54ca-4039-8e17-64230672c432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select reset method'])[1]/following::select[1]</value>
      <webElementGuid>c1e71f61-6ace-41b6-bd58-38911e14c187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What problem are you having with your account?'])[1]/following::select[2]</value>
      <webElementGuid>f17e2fad-0ee2-4077-bd01-cefcfd0ed822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your username'])[1]/preceding::select[1]</value>
      <webElementGuid>8e3d79c6-d4a6-4d77-9555-1bf2d0852781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ospyn Technologies'])[1]/preceding::select[1]</value>
      <webElementGuid>d7b45889-ba3b-42ec-90b3-624260418831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/select</value>
      <webElementGuid>65776287-9cb3-4d3d-a67a-e2facd952a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'resetMethod' and @id = 'form_resetMethod' and (text() = '--Select reset method--Send reset message to mobile' or . = '--Select reset method--Send reset message to mobile')]</value>
      <webElementGuid>03ef47d4-112f-4b11-a266-5d0c5f14fa4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
