<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select Problem--I forgot my password</name>
   <tag></tag>
   <elementGuidId>a1081f29-c1bd-4e3c-9546-1e23a454b4a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formProblem_problems</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='formProblem_problems']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#formProblem_problems</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6b8e8aba-09d9-4b47-95fc-9f69e8c646f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>problems</value>
      <webElementGuid>a20e6ec0-99e6-4280-8f60-99e0ca027479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formProblem_problems</value>
      <webElementGuid>fb5d1302-1ba2-49c6-9dd9-c877203c5a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7ac078a0-4528-4980-b795-67f57221e12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield w100 form-control m-b</value>
      <webElementGuid>2f52608f-f477-41ea-bb0d-f9fb69d4eaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select Problem--I forgot my password</value>
      <webElementGuid>2144eac8-151c-4af9-8560-1373e1b759ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formProblem_problems&quot;)</value>
      <webElementGuid>7984439f-8ac6-454a-82f5-f19a6f92fa46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='formProblem_problems']</value>
      <webElementGuid>c8432a32-9d59-4b63-ba7f-2139ace10464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1info']/div/div/select</value>
      <webElementGuid>be45f8c6-41a4-48b8-89d6-f31611dc36eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What problem are you having with your account?'])[1]/following::select[1]</value>
      <webElementGuid>5358fa35-8d3d-4d75-8331-02c658372205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 2 : Confirm Your Details'])[1]/following::select[1]</value>
      <webElementGuid>6b620005-2969-4f6b-a7d5-c7fd4a2b5443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select reset method'])[1]/preceding::select[1]</value>
      <webElementGuid>ea11f8fe-8b79-4243-9cec-b6b939933eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your username'])[1]/preceding::select[2]</value>
      <webElementGuid>046490f9-805f-4f1a-ab07-8b6bb441b5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>baac2651-14ac-47f8-8f5a-fdc39638cb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'problems' and @id = 'formProblem_problems' and (text() = '--Select Problem--I forgot my password' or . = '--Select Problem--I forgot my password')]</value>
      <webElementGuid>7120cab1-0293-41df-8fa4-d7f2a1dda184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
