<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Motorcycle</name>
   <tag></tag>
   <elementGuidId>d1fb330c-b9da-469f-8434-ffe6889177d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav_motorcycle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav_motorcycle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Motorcycle&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>124a4ff4-6c91-43b7-abe2-3971bf56972f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav_motorcycle</value>
      <webElementGuid>d30c149e-5af0-4790-88eb-e89939530890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Navigation Motorcycle</value>
      <webElementGuid>162a744f-5394-40dc-b44e-3870426f9ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>425ad303-9c79-4092-8bc0-635556b59981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>gotoapp('Motorcycle');</value>
      <webElementGuid>c9e45fa1-5a11-4bc8-ac64-6c786c39f9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Motorcycle</value>
      <webElementGuid>44aa508b-5fcc-4bb9-b1cb-f67c71a0e623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/header[@class=&quot;site-header&quot;]/div[@class=&quot;bottom-header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;main-navigation&quot;]/ul[@class=&quot;menu&quot;]/li[@class=&quot;menu-item&quot;]/a[@id=&quot;nav_motorcycle&quot;]</value>
      <webElementGuid>2f5f8f12-1d74-40fb-9ae8-e6a7a16c8691</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav_motorcycle']</value>
      <webElementGuid>9a1a552e-c0fa-4e0b-9f28-6b81029b78ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/header/div[2]/div/div/ul/li[3]/a</value>
      <webElementGuid>97fc6d2f-8af9-4e27-ab0f-e6f640326fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Motorcycle')]</value>
      <webElementGuid>c94c6e4a-badd-44dc-adab-8ae34eb2b207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Support!'])[1]/following::a[3]</value>
      <webElementGuid>6195a700-2a28-4ff3-8cf3-13f936d8e635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a sample application, Version 1.0.1'])[1]/following::a[4]</value>
      <webElementGuid>0eb9a328-9b60-456e-9e58-fb389123ea50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Demo'])[1]/preceding::a[2]</value>
      <webElementGuid>c5154fc1-f6b7-4b11-b06f-cdebeb2e6493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Motorcycle']/parent::*</value>
      <webElementGuid>d4a284ba-6a5c-4768-8666-61da3c7b7a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>d2c86a05-00e5-4d98-a193-2d491b673a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>d6f8ad8c-b4bb-4f71-9e8e-e4ac1eaba67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav_motorcycle' and @name = 'Navigation Motorcycle' and @href = '#' and (text() = 'Motorcycle' or . = 'Motorcycle')]</value>
      <webElementGuid>5ce233c9-a264-43ac-88e2-b4adc8029b4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
