<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Automation Bookstore_searchBar</name>
   <tag></tag>
   <elementGuidId>abeb96a4-7e69-43e9-9f30-3c83c67e08e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchBar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Filter books..&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a80a246a-6a6e-45ae-ad71-71c01d930c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBar</value>
      <webElementGuid>622ddf62-ad70-4866-bb57-e9846e0be04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>7eb4410c-02b2-48f0-bbde-ad265f2b414f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter books..</value>
      <webElementGuid>fab733db-42d9-4a61-9fb5-67bd29a366de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-focus</value>
      <webElementGuid>e5b257fa-5aca-4c44-9a07-5949510bddb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBar&quot;)</value>
      <webElementGuid>ede23869-2011-4c90-bb2c-ace478f410a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBar']</value>
      <webElementGuid>3611c316-00f0-49ed-95d9-81351e67566a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo-page']/div[2]/form/div/input</value>
      <webElementGuid>c2f53ec0-46a4-4523-bd88-bd514608f53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e1643d9e-1bf0-4723-8cae-2c90875f8d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchBar' and @placeholder = 'Filter books..']</value>
      <webElementGuid>a0df6a62-1c71-460f-bbc7-7d9b9efd24f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
