<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Motorcycle</name>
   <tag></tag>
   <elementGuidId>c824a12b-f5c5-4d0f-8d71-65e095d71ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav_motorcycle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav_motorcycle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Motorcycle&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b44e42bc-5759-4a0c-89ee-3e712604ba8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav_motorcycle</value>
      <webElementGuid>be776e92-31c3-4040-895f-a871032b6106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Navigation Motorcycle</value>
      <webElementGuid>6c3d011b-5f7d-4dbf-8f81-98b268406a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7fba39b3-b928-483f-8ef0-06c01f38625f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>gotoapp('Motorcycle');</value>
      <webElementGuid>beb91efb-5e69-46c7-ac39-50d21506c558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Motorcycle</value>
      <webElementGuid>e3b1e991-5503-4530-8969-58ab57aa9d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/header[@class=&quot;site-header&quot;]/div[@class=&quot;bottom-header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;main-navigation&quot;]/ul[@class=&quot;menu&quot;]/li[@class=&quot;menu-item&quot;]/a[@id=&quot;nav_motorcycle&quot;]</value>
      <webElementGuid>03211977-53c7-4420-be47-e9312784316e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav_motorcycle']</value>
      <webElementGuid>94e4c2f4-d140-4b0d-9574-218d07d719df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/header/div[2]/div/div/ul/li[3]/a</value>
      <webElementGuid>0972117f-0ac6-4310-9952-d09fd39c8dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Motorcycle')]</value>
      <webElementGuid>839ecf9d-ad26-481d-8e98-1608a8655393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Support!'])[1]/following::a[3]</value>
      <webElementGuid>4328d657-7280-4a21-8166-8f9a0a410eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a sample application, Version 1.0.1'])[1]/following::a[4]</value>
      <webElementGuid>21ce8b94-6887-4a36-b9a1-31d1e5a4fe04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Demo'])[1]/preceding::a[2]</value>
      <webElementGuid>2c86f13a-95c6-4cc7-a462-6446fb823867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Motorcycle']/parent::*</value>
      <webElementGuid>90a89a78-1046-413e-89c8-b889a2fba715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>4302c4f5-53ca-4037-8e06-5ec2c0469bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>a1ff9813-6f43-472d-bca8-5b1541c3bfd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav_motorcycle' and @name = 'Navigation Motorcycle' and @href = '#' and (text() = 'Motorcycle' or . = 'Motorcycle')]</value>
      <webElementGuid>4f57a161-4b94-4e94-8b2e-dab3a91c97d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
