<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address_Street Address</name>
   <tag></tag>
   <elementGuidId>c12e2db5-da77-4017-9237-d99d246ac9c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#streetaddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='streetaddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#streetaddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86004a87-211c-4e99-b18d-3219a5b1e68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>streetaddress</value>
      <webElementGuid>5af4e0d9-d4bd-47bc-8e6c-ddca72827816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Street Address</value>
      <webElementGuid>facf77d8-8db5-4436-af79-6bd957c035ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c44575d3-53f5-4ff6-ab28-36732a910445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;streetaddress&quot;)</value>
      <webElementGuid>1ba75a33-df4c-4b23-b1c8-70bbe4b166e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='streetaddress']</value>
      <webElementGuid>45dfff08-6dc3-49b0-bc50-b3e2422b49f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[5]/input</value>
      <webElementGuid>bac8aa6f-b8fc-427c-b51d-0ae10a170f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[5]/input</value>
      <webElementGuid>8c00598d-b29c-4307-be41-8ae41dc94015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'streetaddress' and @name = 'Street Address' and @type = 'text']</value>
      <webElementGuid>d3359800-927c-4803-b3f9-c3b1c05ef586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
