<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Speeding_ideal-check</name>
   <tag></tag>
   <elementGuidId>6e854eaa-1a45-48cc-adb1-fa3c92f906b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ideal-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='insurance-form']/div/section[2]/div[10]/p/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;Speeding&quot;i >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e026252d-0b3b-4934-b906-a0b44dbaf435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ideal-check</value>
      <webElementGuid>f6f37118-d5fb-48bf-9d4a-ae72077082a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insurance-form&quot;)/div[@class=&quot;idealsteps-wrap&quot;]/section[@class=&quot;idealsteps-step&quot;]/div[@class=&quot;field idealforms-field idealforms-field-checkbox&quot;]/p[@class=&quot;group&quot;]/label[@class=&quot;ideal-radiocheck-label&quot;]/span[@class=&quot;ideal-check&quot;]</value>
      <webElementGuid>a4e19e5e-cc4d-482b-a7e7-e6d4a8e32d9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[10]/p/label/span</value>
      <webElementGuid>7a59b883-94a1-4b59-84dd-a1f367060795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/p/label/span</value>
      <webElementGuid>ea02e5d4-c2a7-41bd-adf3-6ad72dd9c056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
