<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Female_ideal-radio</name>
   <tag></tag>
   <elementGuidId>2a5b7529-cb7f-4aa4-8334-9afa35c4403f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='insurance-form']/div/section[2]/div[4]/p/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;Female&quot;i >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dfcc3396-5f6b-4c42-bdd2-46d1d6922ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ideal-radio</value>
      <webElementGuid>1857fd5e-6820-4c63-9f34-4f15d4bd5ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insurance-form&quot;)/div[@class=&quot;idealsteps-wrap&quot;]/section[@class=&quot;idealsteps-step&quot;]/div[@class=&quot;field&quot;]/p[@class=&quot;group&quot;]/label[@class=&quot;ideal-radiocheck-label&quot;]/span[@class=&quot;ideal-radio&quot;]</value>
      <webElementGuid>cea1ce07-89a2-4dcb-add6-58a9f368491b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[4]/p/label[2]/span</value>
      <webElementGuid>1d45cf8c-8428-4bc7-afd9-d9414af6aea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>7f0f6249-0abb-4b30-95da-9bad169e32a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
