<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enter Insurant Data7</name>
   <tag></tag>
   <elementGuidId>3e7a84d6-0a1f-4d32-be45-b5a799dfbb9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enterinsurantdata</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='enterinsurantdata']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Enter Insurant Data 7&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>42acd6ba-f39e-4716-ada6-c5bf9e289a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c52adfe2-9cbd-477e-8a97-c26f58c29346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b12e4801-1247-4390-b966-328fb8a90137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enterinsurantdata</value>
      <webElementGuid>6c39aa88-f09e-4bc5-9d72-cd3cd49c038c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Enter Insurant Data</value>
      <webElementGuid>8b072f80-6feb-4048-ba62-6c7d83e28bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter Insurant Data7</value>
      <webElementGuid>b1f85b0f-3b5d-44b6-943c-9d3271f27405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enterinsurantdata&quot;)</value>
      <webElementGuid>c3c1a36c-8623-445b-8c3c-d15a39285d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='enterinsurantdata']</value>
      <webElementGuid>839774d9-e8d8-4d25-9e6f-aa5193f4e6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='idealsteps-nav']/ul/li[2]/a</value>
      <webElementGuid>3cbd4cee-c4f9-4b32-89bf-767860b2ac1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motorcycle Insurance'])[1]/following::a[2]</value>
      <webElementGuid>8b30c2cc-e27e-4c7f-a0d4-fdb9f28920c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>b4e8b31b-a2d9-457c-a314-7ea2b317c6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make'])[1]/preceding::a[4]</value>
      <webElementGuid>9450de0c-0e40-467b-8abd-89107244e90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option'])[1]/preceding::a[4]</value>
      <webElementGuid>2965c748-6197-404d-a4f8-09cd11ee3936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter Insurant Data']/parent::*</value>
      <webElementGuid>a9de024e-72b5-4b86-b8d2-d5f901a9686b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>1731953c-8485-49a6-a3e0-fde7d1d522f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>55771eb2-38da-465f-ac90-ced1ade75022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'enterinsurantdata' and @name = 'Enter Insurant Data' and (text() = 'Enter Insurant Data7' or . = 'Enter Insurant Data7')]</value>
      <webElementGuid>80d602fe-833d-4bd1-95e1-a400969fe375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
