<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_API Testing in detail using Postman - Tes_e954f1</name>
   <tag></tag>
   <elementGuidId>e8b7c812-f5d6-4cb6-86ad-e0eeb6911597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='udemy-promo-thumbnail']/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;API Testing in detail using Postman - Test Automation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d76f3d9-c820-457b-ae31-65f272ceb0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.udemy.com/course/the-api-master-class-testing-in-detail-using-postman/?couponCode=90466C1B15F593ABFC9A</value>
      <webElementGuid>9d760925-3c8e-4666-81f0-a8e53fb8fd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>API Testing in detail using Postman - Test Automation</value>
      <webElementGuid>84e8f09f-b377-44f0-97de-10f68d682d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udemy-promo-thumbnail&quot;)/p[1]/a[1]</value>
      <webElementGuid>29e2e119-48f5-4a74-9320-442a8b6e0108</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udemy-promo-thumbnail']/p/a</value>
      <webElementGuid>e7a50dee-b28f-422c-806c-8c9f5a73f148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'API Testing in detail using Postman - Test Automation')]</value>
      <webElementGuid>89ebc82a-d732-41bc-be55-4488e8ee4b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mega Sale'])[1]/following::a[1]</value>
      <webElementGuid>80c94037-d9c0-4bfd-9d60-3f3a47e7ab6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playwright with Cucumber BDD &amp; TypeScript - Beginner to Pro'])[1]/preceding::a[1]</value>
      <webElementGuid>13e954d9-e99a-49ce-9e01-f71be5576188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='API Testing in detail using Postman - Test Automation']/parent::*</value>
      <webElementGuid>3c69646f-88aa-4c68-a98d-377e47c04d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.udemy.com/course/the-api-master-class-testing-in-detail-using-postman/?couponCode=90466C1B15F593ABFC9A')]</value>
      <webElementGuid>3595f488-db52-40e3-af91-08d731bd31c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>415a76bf-9095-47e3-8be6-b37bcc307c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.udemy.com/course/the-api-master-class-testing-in-detail-using-postman/?couponCode=90466C1B15F593ABFC9A' and (text() = 'API Testing in detail using Postman - Test Automation' or . = 'API Testing in detail using Postman - Test Automation')]</value>
      <webElementGuid>7ad70a0a-26a8-48a2-b712-6f95f2a358f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
