<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Announcements</name>
   <tag></tag>
   <elementGuidId>8747458c-785f-4f22-9f96-d25aab939c9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='announcementsDiv']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.annLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Announcements&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9ccc4a8-5b7d-4906-93d2-30a71229867d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>annLink</value>
      <webElementGuid>72b4398a-56f4-4d18-aa3b-f0b3aa27eb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>164:0</value>
      <webElementGuid>728a7401-7393-4f83-a6e9-4c38a8fb1ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://customerportal.parasoft.com/lightningportal/s/announcements</value>
      <webElementGuid>1d8026e8-afd1-4a2b-84b7-b8af26b6bc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Announcements</value>
      <webElementGuid>480b743a-ba6f-4f47-8ed5-79aed124021b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;announcementsDiv&quot;)/div[@class=&quot;blockHeader&quot;]/a[@class=&quot;annLink&quot;]</value>
      <webElementGuid>859b7493-0aa4-4a2f-9097-dbea693ef336</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='announcementsDiv']/div/a</value>
      <webElementGuid>b385be49-0407-45de-a761-53e918a6a211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Announcements')])[2]</value>
      <webElementGuid>54e105e1-152a-462b-b450-b892b8b448d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Portal Home'])[2]/following::a[1]</value>
      <webElementGuid>ad7f80a5-1a85-4d5f-baef-a112f5d61bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::a[1]</value>
      <webElementGuid>3ac01435-3c37-495e-a4c5-570f1f669559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Parasoft C/C++test 2024.1 is now available'])[1]/preceding::a[1]</value>
      <webElementGuid>c4496a35-1532-4302-9022-fa93de1526a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='June 4, 2024 -'])[1]/preceding::a[2]</value>
      <webElementGuid>1b45218f-32cd-440a-b051-9c4ae7b7f31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://customerportal.parasoft.com/lightningportal/s/announcements')])[2]</value>
      <webElementGuid>c844e5f1-d0a2-47c2-8f89-7445097f07a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>d9a081c1-43fd-41ee-b9ab-8cb677ac01d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://customerportal.parasoft.com/lightningportal/s/announcements' and (text() = 'Announcements' or . = 'Announcements')]</value>
      <webElementGuid>a5cf7c62-35e9-40bf-bb3c-a0a6b62ae666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
