<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CSS</name>
   <tag></tag>
   <elementGuidId>f0fbfc2e-f912-436f-81d0-5138f8a20457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='library-nav']/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;CSS Tutorial&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#library-nav >> internal:role=link[name=&quot;CSS&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6763362-e791-4376-ac58-31ac58846e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/css/index.htm</value>
      <webElementGuid>84a2a00a-edde-4603-a9f0-dc3990ae5dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>CSS Tutorial</value>
      <webElementGuid>54e610a0-2a02-4eeb-801b-efdc36203891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSS</value>
      <webElementGuid>01500323-0007-43f6-a3d0-1bf10a042fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;library-nav&quot;)/li[3]/a[1]</value>
      <webElementGuid>07d539cd-188a-4765-8399-7b101f51cc7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='library-nav']/li[3]/a</value>
      <webElementGuid>308fbdef-745e-4de3-a03f-fc20e1e84be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'CSS')])[2]</value>
      <webElementGuid>e53c8d46-a679-4b3b-9729-f563b7ce7ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML'])[2]/following::a[1]</value>
      <webElementGuid>88b3e45b-0da4-4f0c-a4ca-4f32b4e1e2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL'])[2]/following::a[2]</value>
      <webElementGuid>3f0814a8-2e2c-4684-b69d-2937f6cedc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript'])[2]/preceding::a[1]</value>
      <webElementGuid>36d9399b-d049-4061-aecd-0603ee2d24bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Python'])[3]/preceding::a[2]</value>
      <webElementGuid>bf1e1a00-c60f-43eb-b780-8304e4c8c3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/css/index.htm')])[2]</value>
      <webElementGuid>30507ec3-dcca-4425-aea1-5e657ff8f61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/ul/li[3]/a</value>
      <webElementGuid>129248f1-cd3d-4e3d-b407-786e14fd7af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/css/index.htm' and @title = 'CSS Tutorial' and (text() = 'CSS' or . = 'CSS')]</value>
      <webElementGuid>21603544-8914-4354-b4ff-f520a63d667d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
