<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SQL</name>
   <tag></tag>
   <elementGuidId>28d8bbd2-3d4d-4966-8a90-fdf85558fe3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='library-nav']/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;SQL Tutorial&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#library-nav >> internal:role=link[name=&quot;SQL&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67604664-98a3-427d-90f5-ef906ea1b1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/sql/index.htm</value>
      <webElementGuid>e00a9607-b656-44e9-9250-df7db7493e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SQL Tutorial</value>
      <webElementGuid>e23ab88e-c0ba-4482-988a-e46ff7665ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SQL</value>
      <webElementGuid>a7109cf3-c024-4ece-8a59-725ca55077ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;library-nav&quot;)/li[1]/a[1]</value>
      <webElementGuid>53a7b8b7-0f24-46e2-ae37-4c88bf857c3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='library-nav']/li/a</value>
      <webElementGuid>3078ae51-8c27-4fb0-8f13-6965efd0239d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SQL')])[7]</value>
      <webElementGuid>9a934a70-ebd0-4121-84c6-f5a742feaa71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/following::a[1]</value>
      <webElementGuid>f0987ab9-2b1e-47f3-ae67-957ce109fc3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show search'])[1]/following::a[1]</value>
      <webElementGuid>46c832c5-faf0-4b53-936a-875a94319bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML'])[2]/preceding::a[1]</value>
      <webElementGuid>a6980dd8-b8ac-4cb0-8e85-eb263df8e755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSS'])[2]/preceding::a[2]</value>
      <webElementGuid>760a357f-6075-4969-a7c3-45814e787f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/sql/index.htm')])[2]</value>
      <webElementGuid>4717df28-ed9b-4ca5-ade1-eb3a34122fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/ul/li/a</value>
      <webElementGuid>6f122369-b52e-4b0e-8079-f7781c27c7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/sql/index.htm' and @title = 'SQL Tutorial' and (text() = 'SQL' or . = 'SQL')]</value>
      <webElementGuid>d7a04939-08b4-43ac-a3f4-eda947c425f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
