<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Postman</name>
   <tag></tag>
   <elementGuidId>eb5eab38-3796-49c5-9aff-d3c001164769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ud-btn.ud-btn-large.ud-btn-secondary.ud-btn-round.ud-heading-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content-anchor']/div[5]/div/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=/^Postman$/ >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b0421de-bb45-40e7-be6f-6093338b8709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/topic/postman/</value>
      <webElementGuid>8eb093dd-cfdb-47c5-80a0-f48e3e7e3ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ud-btn ud-btn-large ud-btn-secondary ud-btn-round ud-heading-md</value>
      <webElementGuid>851e36b4-9139-47a7-8729-a5fe5f504c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Postman</value>
      <webElementGuid>8ecc1377-ae14-47f5-973c-5ba141643342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-anchor&quot;)/div[@class=&quot;paid-course-landing-page__body&quot;]/div[@class=&quot;course-landing-page__main-content&quot;]/div[@class=&quot;topic-navigation-module--topic-navigation--wCbdV&quot;]/ul[@class=&quot;ud-unstyled-list pill-group-module--pill-group--q7hFg&quot;]/li[@class=&quot;pill-group-module--pill--4e6tF&quot;]/a[@class=&quot;ud-btn ud-btn-large ud-btn-secondary ud-btn-round ud-heading-md&quot;]</value>
      <webElementGuid>564a7502-1066-47a3-ac63-892871d30d4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content-anchor']/div[5]/div/div[2]/ul/li/a</value>
      <webElementGuid>4071fa2d-e758-45de-8b35-597da32c6151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore related topics'])[1]/following::a[1]</value>
      <webElementGuid>23d93c94-e96c-4627-8fd8-936c2cc0be32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='And plenty more!'])[1]/following::a[1]</value>
      <webElementGuid>daa5c2e2-ee51-431b-a3b7-5730484976c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software Testing'])[3]/preceding::a[1]</value>
      <webElementGuid>acf4a345-110f-4c06-bd6a-a35b517b0970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/topic/postman/')])[2]</value>
      <webElementGuid>2a483ecc-c05b-4009-af1e-479047c2ff28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>d30faf8c-7cf6-4f7a-95a2-04f888b0f362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/topic/postman/' and (text() = 'Postman' or . = 'Postman')]</value>
      <webElementGuid>cd009375-f9e9-4b73-a1e2-54532e19fd1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
