<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_API Testing in detail using Postman - Te_3ef861</name>
   <tag></tag>
   <elementGuidId>b5fbea61-e3b4-4cc0-a912-f8c682568b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.ud-heading-xxl.clp-lead__title.clp-lead__title--small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content-anchor']/div/div/div/div[3]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;API Testing in detail using Postman - Test Automation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>d6c59df6-edac-4f2e-b6bb-053406f76aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ud-heading-xxl clp-lead__title clp-lead__title--small</value>
      <webElementGuid>0137ae48-f9cf-4ae0-a52a-fda51623ca55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-purpose</name>
      <type>Main</type>
      <value>lead-title</value>
      <webElementGuid>e179bdc1-834a-4142-864c-021a924d6a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>API Testing in detail using Postman - Test Automation</value>
      <webElementGuid>1ff27c0a-d6fe-41d6-9965-7efd78583ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-anchor&quot;)/div[@class=&quot;top-container dark-background&quot;]/div[@class=&quot;background-inner-position-container&quot;]/div[1]/div[@class=&quot;course-landing-page__main-content dark-background-inner-text-container&quot;]/div[@class=&quot;ud-text-sm clp-lead&quot;]/h1[@class=&quot;ud-heading-xxl clp-lead__title clp-lead__title--small&quot;]</value>
      <webElementGuid>ebe14696-cf3d-4d6f-ad44-5dbac34392ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content-anchor']/div/div/div/div[3]/div/h1</value>
      <webElementGuid>b25d0651-4b0e-43b1-901a-aacfa2f0e077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview this course'])[1]/following::h1[1]</value>
      <webElementGuid>baabb928-42f2-4b0d-8a84-4754850acb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postman'])[1]/following::h1[1]</value>
      <webElementGuid>b84b1b38-2ec8-46f2-b3d9-d5c5caa5bd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating: 4.7 out of 5'])[1]/preceding::h1[1]</value>
      <webElementGuid>00099067-a3c2-4ebb-a5de-dbf8ed559e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(53 ratings)'])[1]/preceding::h1[1]</value>
      <webElementGuid>2ceedb91-d875-4dde-992a-9bc44cf9e65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='API Testing in detail using Postman - Test Automation']/parent::*</value>
      <webElementGuid>a838623b-5a89-416c-8843-6adcdb86cb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>a85033bd-6932-4f2a-ba07-78846cd01894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'API Testing in detail using Postman - Test Automation' or . = 'API Testing in detail using Postman - Test Automation')]</value>
      <webElementGuid>2cff1b73-c14b-4dba-af13-497cd799ca1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
