<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Languages</name>
   <tag></tag>
   <elementGuidId>399e8dce-04d2-42dd-932c-dda475aeaf60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='About PageSpeed Insights'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Languages&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9056b87d-8582-4612-b41d-8aff2f754f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://developers.google.com/speed/docs/insights/languages</value>
      <webElementGuid>603ecf99-a8c2-47c4-b151-04874c7c1731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>devsite-nav-title gc-analytics-event</value>
      <webElementGuid>d73d3b6c-777f-4cca-bce4-628db2d915d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>Site-Wide Custom Events</value>
      <webElementGuid>41f95f7b-7a55-4b4b-9d31-fc31961da4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Book nav link, pathname: /speed/docs/insights/languages</value>
      <webElementGuid>544cbd24-8973-4262-b332-ba2a2a98008a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>track-type</name>
      <type>Main</type>
      <value>bookNav</value>
      <webElementGuid>91ea3ebf-0002-4539-a5a6-206abb7b1ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>track-name</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>f221aad6-f431-40bf-8161-3b6111d9da3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>track-metadata-eventdetail</name>
      <type>Main</type>
      <value>/speed/docs/insights/languages</value>
      <webElementGuid>acd51fce-cb7c-4d72-8faf-cb12012cf26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Languages</value>
      <webElementGuid>2bb87cbf-a448-41ed-85db-c10ae6eb9c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;viewport--desktop tenant--developers&quot;]/section[@class=&quot;devsite-wrapper&quot;]/devsite-book-nav[1]/nav[@class=&quot;devsite-book-nav devsite-nav nocontent&quot;]/div[@class=&quot;devsite-book-nav-wrapper&quot;]/div[@class=&quot;devsite-mobile-nav-bottom&quot;]/ul[@class=&quot;devsite-nav-list&quot;]/li[@class=&quot;devsite-nav-item&quot;]/a[@class=&quot;devsite-nav-title gc-analytics-event&quot;]</value>
      <webElementGuid>08350d6e-177a-4424-9d17-c17f741412c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About PageSpeed Insights'])[1]/following::a[1]</value>
      <webElementGuid>fd460d7e-bde7-4c89-ae83-b740afd0b2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOCS'])[2]/following::a[2]</value>
      <webElementGuid>da448a72-07d1-44c2-9dbc-ac8664a30e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release Notes'])[1]/preceding::a[1]</value>
      <webElementGuid>a2757ca6-e79b-49a0-bd75-de8004857869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://developers.google.com/speed/docs/insights/languages')]</value>
      <webElementGuid>0f4e3116-c713-40f4-bdf3-ed6b43f35e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>ece3bab7-7395-4d74-bf37-a2ea9532a220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://developers.google.com/speed/docs/insights/languages' and (text() = 'Languages' or . = 'Languages')]</value>
      <webElementGuid>ebd91629-1ceb-448b-9a7b-70d229813b4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
