<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_YourMessage (required)_upcoming__regist_141afe</name>
   <tag></tag>
   <elementGuidId>69a8a7f5-2a13-4d65-8fb2-3a41ddbe63b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.upcoming__registration--captcha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='enroll-form']/div[8]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Captcha for submitting form&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4bd8f5ce-a330-4c8d-a238-f7656498bc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/captcha</value>
      <webElementGuid>ed83d021-e32a-4607-81ff-6f513602a3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upcoming__registration--captcha</value>
      <webElementGuid>222434fc-ad21-4f77-a031-436dd70b3284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Captcha for submitting form</value>
      <webElementGuid>94771976-1677-48cd-912c-0c540581e9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enroll-form&quot;)/div[@class=&quot;upcoming__registration--input__container code&quot;]/img[@class=&quot;upcoming__registration--captcha&quot;]</value>
      <webElementGuid>b880cb40-38be-4197-80a3-2abd4541e26f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='enroll-form']/div[8]/img</value>
      <webElementGuid>2565166e-46b6-4b66-b1f3-7613ba9147fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Captcha for submitting form']</value>
      <webElementGuid>b5fa15ea-05a5-469d-82a0-1a632496e9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/img</value>
      <webElementGuid>a4e985f3-3b82-4379-8d7e-6bd9a8362f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/captcha' and @alt = 'Captcha for submitting form']</value>
      <webElementGuid>35282934-7b6e-4688-ac12-d362c5027da2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
