<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Elements_banner-image</name>
   <tag></tag>
   <elementGuidId>b31934a8-f0bb-4566-bb97-f065c7466868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.banner-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Selenium Online Training&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>612bff2b-ba70-49c2-ab93-9d2d806d5176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner-image</value>
      <webElementGuid>0e022a53-56a5-4c6b-88fd-101947ed0c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/WB.svg</value>
      <webElementGuid>1a842db0-1348-47d7-9795-9b4eeb88a105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Selenium Online Training</value>
      <webElementGuid>38a2edce-0ade-4a4f-bf01-a2789ca030fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;body-height&quot;]/div[@class=&quot;home-content&quot;]/div[@class=&quot;home-banner&quot;]/a[1]/img[@class=&quot;banner-image&quot;]</value>
      <webElementGuid>915f3f47-26f1-4dae-b092-25347024f07b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/a/img</value>
      <webElementGuid>be2d68c8-72a2-4a41-a51f-9f6041c3de75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Selenium Online Training']</value>
      <webElementGuid>6a98c730-cbdf-4716-a24e-a8dc1be4a592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/img</value>
      <webElementGuid>55a4ef9f-f6c1-41fc-961c-4b28528efb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/WB.svg' and @alt = 'Selenium Online Training']</value>
      <webElementGuid>16f770f0-c00e-406f-852f-47134166a82c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
