<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>html_window.top.postMessage(msg_typeresize-_a7bd98</name>
   <tag></tag>
   <elementGuidId>ba8c1e6d-890e-4491-ba0b-e10968e84a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>html</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>html</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>html</value>
      <webElementGuid>5092598a-04f7-4786-8911-1981d7265e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>window.top.postMessage('{&quot;msg_type&quot;:&quot;resize-me&quot;,&quot;key_value&quot;:[{&quot;key&quot;:&quot;r_nh&quot;,&quot;value&quot;:&quot;0&quot;},{&quot;key&quot;:&quot;r_ifr&quot;,&quot;value&quot;:&quot;true&quot;},{&quot;key&quot;:&quot;qid&quot;,&quot;value&quot;:&quot;CK6Got-9ookDFQVQnQkdWzshug&quot;}],&quot;googMsgType&quot;:&quot;sth&quot;}', '*');window.top.postMessage('{&quot;msg_type&quot;:&quot;adsense-labs&quot;,&quot;key_value&quot;:[{&quot;key&quot;:&quot;settings&quot;,&quot;value&quot;:&quot;[\\\&quot;ca-pub-1056034821646296\\\&quot;,[[1]]]&quot;}],&quot;googMsgType&quot;:&quot;sth&quot;}', '*');#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon katalon-div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} katalon-div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} katalon-div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}/html[1]</value>
      <webElementGuid>a98958e8-8f76-4739-9602-62862aab6b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]</value>
      <webElementGuid>d4226ede-007d-4fa5-9147-a9abef8ceaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Xpath and Css Selector Tester Tool for_de1387/iframe_Automation Training_aswift_1</value>
      <webElementGuid>aa2d30a7-66be-45b1-a710-564693cd8f3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//html</value>
      <webElementGuid>86b83e83-999f-424c-a225-92b313ff2dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//html[(text() = concat(&quot;window.top.postMessage(&quot; , &quot;'&quot; , &quot;{&quot;msg_type&quot;:&quot;resize-me&quot;,&quot;key_value&quot;:[{&quot;key&quot;:&quot;r_nh&quot;,&quot;value&quot;:&quot;0&quot;},{&quot;key&quot;:&quot;r_ifr&quot;,&quot;value&quot;:&quot;true&quot;},{&quot;key&quot;:&quot;qid&quot;,&quot;value&quot;:&quot;CK6Got-9ookDFQVQnQkdWzshug&quot;}],&quot;googMsgType&quot;:&quot;sth&quot;}&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;*&quot; , &quot;'&quot; , &quot;);window.top.postMessage(&quot; , &quot;'&quot; , &quot;{&quot;msg_type&quot;:&quot;adsense-labs&quot;,&quot;key_value&quot;:[{&quot;key&quot;:&quot;settings&quot;,&quot;value&quot;:&quot;[\\\&quot;ca-pub-1056034821646296\\\&quot;,[[1]]]&quot;}],&quot;googMsgType&quot;:&quot;sth&quot;}&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;*&quot; , &quot;'&quot; , &quot;);#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon katalon-div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} katalon-div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} katalon-div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}/html[1]&quot;) or . = concat(&quot;window.top.postMessage(&quot; , &quot;'&quot; , &quot;{&quot;msg_type&quot;:&quot;resize-me&quot;,&quot;key_value&quot;:[{&quot;key&quot;:&quot;r_nh&quot;,&quot;value&quot;:&quot;0&quot;},{&quot;key&quot;:&quot;r_ifr&quot;,&quot;value&quot;:&quot;true&quot;},{&quot;key&quot;:&quot;qid&quot;,&quot;value&quot;:&quot;CK6Got-9ookDFQVQnQkdWzshug&quot;}],&quot;googMsgType&quot;:&quot;sth&quot;}&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;*&quot; , &quot;'&quot; , &quot;);window.top.postMessage(&quot; , &quot;'&quot; , &quot;{&quot;msg_type&quot;:&quot;adsense-labs&quot;,&quot;key_value&quot;:[{&quot;key&quot;:&quot;settings&quot;,&quot;value&quot;:&quot;[\\\&quot;ca-pub-1056034821646296\\\&quot;,[[1]]]&quot;}],&quot;googMsgType&quot;:&quot;sth&quot;}&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;*&quot; , &quot;'&quot; , &quot;);#katalon{font-family:monospace;font-size:13px;background-color:rgba(0,0,0,.7);position:fixed;top:0;left:0;right:0;display:block;z-index:999999999;line-height: normal} #katalon katalon-div{padding:0;margin:0;color:#fff;} #katalon kbd{display:inline-block;padding:3px 5px;font:13px Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace;line-height:10px;color:#555;vertical-align:middle;background-color:#fcfcfc;border:1px solid #ccc;border-bottom-color:#bbb;border-radius:3px;box-shadow:inset 0 -1px 0 #bbb;font-weight: bold} katalon-div#katalon-spy_elementInfoDiv {color: lightblue; padding: 0px 5px 5px} katalon-div#katalon-spy_instructionDiv {padding: 5px 5px 2.5px}/html[1]&quot;))]</value>
      <webElementGuid>f642ef31-1b20-44a1-966b-64fecbee0114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
