<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nurturing Business of Tomorrow</name>
   <tag></tag>
   <elementGuidId>80543a35-9e19-497c-88c0-3cfdb4f65215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[3]/div/div/div/div/div/ul/li[4]/div/div/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Nurturing Business of Tomorrow&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06409b5d-e2d1-4e87-a6ed-e9677ae4d185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nurturing Business of Tomorrow</value>
      <webElementGuid>2132a7f1-bac6-4fb5-9924-3221eaa78356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;application--wrap&quot;]/div[1]/div[1]/div[@class=&quot;navWrap&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;menus&quot;]/ul[1]/li[@class=&quot;solutions-li&quot;]/div[@class=&quot;menu-box&quot;]/div[@class=&quot;-layout-wrap&quot;]/ul[@class=&quot;meun-ul&quot;]/li[1]/a[1]/span[1]</value>
      <webElementGuid>bf396c8f-80f9-4817-af7c-76cb0a139d89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/ul/li[4]/div/div/ul/li/a/span</value>
      <webElementGuid>f5eeffd4-01bd-4ee7-9e6d-42738d81b3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PingPong Ecosystem'])[1]/following::span[1]</value>
      <webElementGuid>9ef7e1e8-9917-4cda-8a45-e8f535ce7ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value Added Services'])[1]/following::span[2]</value>
      <webElementGuid>4aa9db8a-765f-4b26-a66b-3c2876e5eaf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Leaders Program'])[1]/preceding::span[1]</value>
      <webElementGuid>213ff696-2836-4f07-825d-1f3d49406327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Success Stories'])[1]/preceding::span[2]</value>
      <webElementGuid>6a458dd4-d1bb-44eb-bb05-8d2c46006fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nurturing Business of Tomorrow']/parent::*</value>
      <webElementGuid>28c78efd-caa8-47ab-a146-d1ce55da1e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/ul/li/a/span</value>
      <webElementGuid>b7731c19-b22d-4c0a-9812-57dbf130fc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Nurturing Business of Tomorrow' or . = 'Nurturing Business of Tomorrow')]</value>
      <webElementGuid>e22def04-5325-453d-bb6b-392d08d541a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
