<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_www.udemy.com</name>
   <tag></tag>
   <elementGuidId>b79db87e-57fd-48f8-9039-258c390326cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.zone-name-title.h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifying you are human. This may take a few seconds.'])[1]/preceding::h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;www.udemy.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>94d3c3b9-a398-4331-8b47-8f92dc0eeba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zone-name-title h1</value>
      <webElementGuid>9981cd7b-f78a-4d59-a608-3cac87b1fd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>www.udemy.com</value>
      <webElementGuid>10c6bc8d-73e6-4716-a1f6-b87da6f69d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no-js&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;main-content&quot;]/h1[@class=&quot;zone-name-title h1&quot;]</value>
      <webElementGuid>173c3b87-7d0d-48f6-994b-a1132c98ae8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifying you are human. This may take a few seconds.'])[1]/preceding::h1[1]</value>
      <webElementGuid>5b8614d5-aa1f-4615-b729-4186430ea86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.udemy.com needs to review the security of your connection before proceeding.'])[1]/preceding::h1[1]</value>
      <webElementGuid>bb2a38bc-f74c-447b-b997-93a55568f426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='www.udemy.com']/parent::*</value>
      <webElementGuid>6503811b-dc54-4b9a-b03c-a2c66a5f1ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b2f396ab-be23-4396-a2eb-9f8c1fc22b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'www.udemy.com' or . = 'www.udemy.com')]</value>
      <webElementGuid>c79a2186-c28c-4067-9471-7f66959dea5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
