<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get Started</name>
   <tag></tag>
   <elementGuidId>e25278f9-7b6e-492f-aa61-cf9121a3f914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ctaBtnProtipsSubscribeNow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctaBtnProtipsSubscribeNow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Get Started&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b55aad5-c2ec-4423-a813-62f22d562045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>831c7413-e48a-4d0e-abf6-83ca621cfd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>487d8d94-2444-43cf-be13-fc9fbf32e9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctaBtnProtipsSubscribeNow</value>
      <webElementGuid>0c9c1344-5743-4269-b956-a91d0590e7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blue-btn</value>
      <webElementGuid>73d95e47-7c5b-4c9c-9970-74487384eca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>verifyotp()</value>
      <webElementGuid>5f0c52f9-d501-4c56-b88b-4aab1c240631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Started</value>
      <webElementGuid>f3e50038-8b38-4a4f-87e2-e1ca13927769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctaBtnProtipsSubscribeNow&quot;)</value>
      <webElementGuid>89c83cdf-41bc-4b7c-900d-b8aebac959d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ctaBtnProtipsSubscribeNow']</value>
      <webElementGuid>9c5a574f-d1de-408d-9066-475035ddaa99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmregister']/button</value>
      <webElementGuid>6ae6bd0e-6ac3-4c95-a437-ae05ba4b43e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I accept to receive marketing news and updates from StoxBox to my email address'])[1]/following::button[1]</value>
      <webElementGuid>06ee48b4-cefd-4cbe-8bc9-f7fb8abfd70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Free Demat Account'])[1]/following::button[1]</value>
      <webElementGuid>2b5d0171-e29d-465d-a07f-93bdb172f3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Wealth with StoxBox'])[1]/preceding::button[1]</value>
      <webElementGuid>fb464e97-343e-42a7-9ef5-a65dd84d852a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Award Winning Research'])[1]/preceding::button[1]</value>
      <webElementGuid>7f5659c5-c5d8-4ba6-ac52-f7c944da64d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get Started']/parent::*</value>
      <webElementGuid>1547dbf6-791f-4637-86e2-78155bbce312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>13b7b5b4-d2a9-4bef-9ff8-8e56094778d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @href = 'javascript:void(0)' and @id = 'ctaBtnProtipsSubscribeNow' and (text() = 'Get Started' or . = 'Get Started')]</value>
      <webElementGuid>fb6bb62d-224d-4136-b56c-54742c9f618b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
