<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_6 digit OTP has been sent to your phone</name>
   <tag></tag>
   <elementGuidId>101d38d0-f731-4d3f-935b-e9550bf8b6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='otpmessage']/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;6 digit OTP has been sent to your phone&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>91d62b70-0f7f-40b4-bfed-4ab508e92bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6 digit OTP has been sent to your phone</value>
      <webElementGuid>0b959d80-d1e4-4a63-9cd5-18b947347800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otpmessage&quot;)/strong[1]</value>
      <webElementGuid>f687f973-a094-46d8-bdc9-e0075e31d9ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='otpmessage']/strong</value>
      <webElementGuid>7a0a28ea-fbc8-4281-8c05-6cff87c93891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Free Demat Account'])[1]/following::strong[1]</value>
      <webElementGuid>5bc5d72e-e643-4b40-9d8d-311cb369d8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I accept to receive marketing news and updates from StoxBox to my email address'])[1]/preceding::strong[1]</value>
      <webElementGuid>42b5c7b4-0f7d-45f9-b06b-ccbd703d907c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[1]/preceding::strong[1]</value>
      <webElementGuid>ab9289d9-c9d7-4551-bf6a-8226ddaf1838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6 digit OTP has been sent to your phone']/parent::*</value>
      <webElementGuid>06e35fdf-fa74-4790-b13c-ab6ff27df850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>03f1b917-ef23-4792-877e-64d8888b937a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '6 digit OTP has been sent to your phone' or . = '6 digit OTP has been sent to your phone')]</value>
      <webElementGuid>9ea1a656-7c1d-4477-b1b2-5f7409bb4f0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
