<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Automotive</name>
   <tag></tag>
   <elementGuidId>09f992b5-e07a-4dde-a4b4-414eb89624e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Automotive')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.nav-megamenu.nav-industries.active > div.megamenu-wrap > div.megamenu > div.menu > ul > li > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Automotive&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55a70a99-f969-4547-9e4f-5142a4f76bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.parasoft.com/industries/embedded/automotive/</value>
      <webElementGuid>a8d141df-d4a3-4c6c-b583-66e25eed8e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automotive</value>
      <webElementGuid>9102f6e5-cae3-4f34-8206-fea44372dd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;b-page&quot;]/header[@class=&quot;b-page-head&quot;]/div[@class=&quot;HEADER&quot;]/div[@class=&quot;b-frame&quot;]/div[@class=&quot;inset&quot;]/nav[@class=&quot;primary&quot;]/ul[1]/li[@class=&quot;nav-megamenu nav-industries active&quot;]/div[@class=&quot;megamenu-wrap&quot;]/div[@class=&quot;megamenu&quot;]/div[@class=&quot;menu&quot;]/ul[1]/li[1]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>bdbb0b73-7e90-420d-8b56-9a263ee052d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Automotive')]</value>
      <webElementGuid>2b7bbac4-5c4f-4dc2-8a2f-389f42f21918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn More'])[3]/following::a[1]</value>
      <webElementGuid>f1e38bd9-40ea-4c54-9262-31a672cb3a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Industries'])[1]/following::a[2]</value>
      <webElementGuid>7ef245d7-6987-43de-ab3f-f8396493cc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Civil Aviation'])[1]/preceding::a[1]</value>
      <webElementGuid>69651ae0-135d-4346-aaa8-286185d9346d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Industrial Automation'])[1]/preceding::a[2]</value>
      <webElementGuid>710cb827-9f4c-42a1-964f-f2c7c087058e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automotive']/parent::*</value>
      <webElementGuid>fee87a1a-b0de-42b3-95b1-54c0dd30aead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.parasoft.com/industries/embedded/automotive/')]</value>
      <webElementGuid>61aada8e-c9b2-41aa-b405-8628f1b12ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div[2]/ul/li/ul/li/a</value>
      <webElementGuid>979d12b7-592c-44c8-97f2-772168f3e834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.parasoft.com/industries/embedded/automotive/' and (text() = 'Automotive' or . = 'Automotive')]</value>
      <webElementGuid>e1911a9b-af56-4f94-a8f8-f67a7cf70be6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
