<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>db68eb0f-3b91-463d-a4b2-f8938edb0ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nextenterproductdata</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nextenterproductdata']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Next »&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9216b428-b991-4145-856d-7a4de37c7b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nextenterproductdata</value>
      <webElementGuid>a010197b-28f2-48cf-95ca-ace9e5475ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Next (Enter Product Data)</value>
      <webElementGuid>60f21fc8-7cd3-48f1-a49f-efca7171aeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3391c20-9b5a-4aac-b9bc-2b4be5a52247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>a456f6ad-616a-4f76-80c8-db60bfb749a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next »</value>
      <webElementGuid>0f60d923-fdea-43d3-b64a-3feb949e716d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nextenterproductdata&quot;)</value>
      <webElementGuid>bf9bb393-efca-4728-b6cc-977773864200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nextenterproductdata']</value>
      <webElementGuid>66455641-0d1f-4f07-aa4d-d4d6a9bfc609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[13]/button[2]</value>
      <webElementGuid>c8ba1731-a4cd-484c-8632-f0d2e80e5afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='« Prev'])[1]/following::button[1]</value>
      <webElementGuid>c43c53c3-f017-496b-ae4e-347d3350412c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/following::button[2]</value>
      <webElementGuid>fb01c2d1-34b6-4d5c-a61a-c22aa3a02829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date'])[1]/preceding::button[1]</value>
      <webElementGuid>fd349279-0bd1-40b2-ad09-29bfa5ce0317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is mandatory'])[7]/preceding::button[2]</value>
      <webElementGuid>a50e497d-4c62-479a-bb98-051a4a4ae1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>e71d0096-b053-449b-a10a-699ffb1d1ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'nextenterproductdata' and @name = 'Next (Enter Product Data)' and @type = 'button' and (text() = 'Next »' or . = 'Next »')]</value>
      <webElementGuid>e7fd0fdd-cf29-4b9b-bfda-5ee52a694b93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
