<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address_Street Address</name>
   <tag></tag>
   <elementGuidId>05796b3f-442e-4787-82ae-1c45d471ee07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#streetaddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='streetaddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#streetaddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c64a5fe-36d8-43e2-ab4c-8494cc026fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>streetaddress</value>
      <webElementGuid>7f4c5ad6-fa39-4b27-a407-12119c9b1ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Street Address</value>
      <webElementGuid>336a163e-67fc-4cd5-90ea-c39289725a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d73c9c47-1147-450b-8bb6-cd171e14d84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;streetaddress&quot;)</value>
      <webElementGuid>f4ec2784-000e-422a-98cb-0dc4d0696879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='streetaddress']</value>
      <webElementGuid>2559bed3-64f5-4e38-8ba6-f924531705ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[5]/input</value>
      <webElementGuid>c647ae3f-4e45-41e8-8e86-e8b9996759ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[5]/input</value>
      <webElementGuid>1fd2d54c-3e17-4b8c-bdc8-bbd5d2c519d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'streetaddress' and @name = 'Street Address' and @type = 'text']</value>
      <webElementGuid>91b08afa-7b3a-406e-a730-2cfcb209e3fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
