<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_Date of Birth</name>
   <tag></tag>
   <elementGuidId>6c73b272-bb71-48e7-ae52-b54b0b78e495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;MM/DD/YYYY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37e88db2-359c-4220-9268-2df2514e44fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthdate</value>
      <webElementGuid>06a55ed0-7d79-4167-b6f3-2ff353c8d72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>10ff94fb-0cfd-4c25-814c-db427d4bff45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e16ed77-d015-4d0e-b524-ef6a86861acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD/YYYY</value>
      <webElementGuid>bf814c15-4d02-4406-9309-c384ff891600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker hasDatepicker</value>
      <webElementGuid>c3a1c281-16e5-41bf-ba47-5c5283155802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthdate&quot;)</value>
      <webElementGuid>5cfe37c1-c9eb-4b8d-9447-da3b666c8baf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthdate']</value>
      <webElementGuid>9ddda206-b2b8-49d7-9bd3-bf55af78ba85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[3]/input</value>
      <webElementGuid>c04f919c-d9f0-44bf-8ab4-6a1a2a220397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[3]/input</value>
      <webElementGuid>e3476f49-dd26-4122-8d5d-384cb425c898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'birthdate' and @name = 'Date of Birth' and @type = 'text' and @placeholder = 'MM/DD/YYYY']</value>
      <webElementGuid>21b7f772-185e-400d-8771-3bda12bd43ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
