<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Female_ideal-radio</name>
   <tag></tag>
   <elementGuidId>8ab3ce1d-c245-48ad-a96e-9cd144319e99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='insurance-form']/div/section[2]/div[4]/p/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;Female&quot;i >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f222a087-1564-48ac-a727-165df6130845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ideal-radio</value>
      <webElementGuid>e97a1d95-e704-4d22-8b1b-dd75915a11d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insurance-form&quot;)/div[@class=&quot;idealsteps-wrap&quot;]/section[@class=&quot;idealsteps-step&quot;]/div[@class=&quot;field&quot;]/p[@class=&quot;group&quot;]/label[@class=&quot;ideal-radiocheck-label&quot;]/span[@class=&quot;ideal-radio&quot;]</value>
      <webElementGuid>1be29230-5535-4a45-884e-6d1260b69001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[4]/p/label[2]/span</value>
      <webElementGuid>c2d1f496-3245-4c42-92ab-b3915a09db58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>aabf3fb4-0ff9-482e-9208-74d6b2cfc8d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
