<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Copy Link_WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb</name>
   <tag></tag>
   <elementGuidId>1feb6760-d53d-4bad-b6aa-48fbda3dc603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.WpHeLc.VfPpkd-mRLv6.VfPpkd-RLmnJb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='kO001e']/span/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Docs&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b13f19c8-bd14-48f5-987a-5f55134b9e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb</value>
      <webElementGuid>bfc9d6e6-6593-49e1-a9c6-e12ede744aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://developers.google.com/speed/docs/insights/v5/about</value>
      <webElementGuid>d784e5f2-4f99-4249-828d-c61c88be7fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f209bfed-a0c3-48a3-837b-562ea310bbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Docs</value>
      <webElementGuid>5dd63e7f-7a35-4589-8a14-708f9f071510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>hSRGPd</value>
      <webElementGuid>a295dcb9-101e-4b7a-a7df-84c18de956d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kO001e&quot;)/span[@class=&quot;yTTzpb&quot;]/div[@class=&quot;VfPpkd-dgl2Hf-ppHlrf-sM5MNb&quot;]/div[@class=&quot;VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-dgl2Hf ksBjEc lKxP2d LQeN7 jpGVBd VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc VfPpkd-ksKsZd-mWPk3d-OWXEXe-AHe6Kc-XpnDCe VfPpkd-ksKsZd-mWPk3d&quot;]/a[@class=&quot;WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb&quot;]</value>
      <webElementGuid>4da89315-0bde-437e-baaf-9e82264ff869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='kO001e']/span/div[2]/div/a</value>
      <webElementGuid>253bf35f-cba0-4567-94da-7934aa285e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://developers.google.com/speed/docs/insights/v5/about')]</value>
      <webElementGuid>cacae65c-7aaf-47ad-9be8-a094a6d6ea75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>f0221c03-5117-409d-8da8-6103da9eb103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://developers.google.com/speed/docs/insights/v5/about']</value>
      <webElementGuid>bcd3a607-4322-4b80-b93f-75aa364e857a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
